name: build-and-bundle
on: 
  pull_request:
  push:
    branches:
      - ros2_foxy
  schedule:
    - cron: '0 2,14 * * *'  # run at 2am & 2pm UTC i.e. 7pm & 7am PST everyday

jobs:
  build_and_bundle_ros2:
    strategy:
      matrix:
        distro: ['foxy']
        gazebo: [11]
        include:
        - distro: foxy
          gazebo: 11
          ubuntu_distro: focal
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'schedule' || github.ref == 'refs/heads/ros2_foxy' }}
    name: 'Build and Bundle (ROS2 Foxy)'
    container:
      image: rostooling/setup-ros-docker:ubuntu-${{ matrix.ubuntu_distro }}-ros-${{ matrix.distro }}-ros-base-latest
    outputs:
      robot_ws_build_result: ${{ steps.robot_ws_build.outcome }}
      simulation_ws_build_result: ${{ steps.simulation_ws_build.outcome }}
    steps:
    - name: Checkout Branch
      uses: actions/checkout@v1
      with:
        ref: 'ros2_foxy'
    - name: Setup Permissions
      run: |
        # TODO(ros-tooling/setup-ros-docker#7): calling chown is necessary for now
        sudo chown -R rosbuild:rosbuild "$HOME" .
    - name: Scan using git-secrets
      uses: aws-robotics/aws-robomaker-github-actions/git-secrets-scan-action@2.5
    - id: robot_ws_build
      name: Build and Bundle Robot Workspace
      uses: aws-robotics/aws-robomaker-github-actions/robomaker-sample-app-ci@2.5
      with:
        ros-distro: ${{ matrix.distro }}
        gazebo-version: ${{ matrix.gazebo }}
        workspace-dir: robot_ws
        generate-sources: true
        colcon-bundle-retries: 3
        ubuntu-distro: ${{ matrix.ubuntu_distro }}
    - id: simulation_ws_build
      name: Build and Bundle Simulation Workspace
      uses: aws-robotics/aws-robomaker-github-actions/robomaker-sample-app-ci@2.5
      with:
        ros-distro: ${{ matrix.distro }}
        gazebo-version: ${{ matrix.gazebo }}
        workspace-dir: simulation_ws
        colcon-bundle-retries: 3
        ubuntu-distro: ${{ matrix.ubuntu_distro }}